name: polygon
description: A simple way to draw polygon shapes, to clip them.
version: 0.0.1
homepage: https://github.com/letsar/polygon
repository: https://github.com/letsar/polygon
issue_tracker: https://github.com/letsar/polygon/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
